-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 11:58:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EasyGardenDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EasyGardenDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EasyGardenDB` DEFAULT CHARACTER SET utf8 ;
USE `EasyGardenDB` ;

-- -----------------------------------------------------
-- Table `EasyGardenDB`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EasyGardenDB`.`status` (
  `staid` VARCHAR(2) NOT NULL COMMENT 'Id del status',
  `stades` VARCHAR(20) NULL COMMENT 'Descripción del status',
  PRIMARY KEY (`staid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EasyGardenDB`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EasyGardenDB`.`persona` (
  `perid` INT NOT NULL AUTO_INCREMENT,
  `pernom` VARCHAR(50) NULL COMMENT 'Nombre de la persona\n',
  `perapp` VARCHAR(45) NULL COMMENT 'Apellido paterno de la persona',
  `perapm` VARCHAR(45) NULL COMMENT 'Apellido materno de la persona',
  `pertel` VARCHAR(18) NULL COMMENT 'Teléfono de la persona',
  `percel` VARCHAR(18) NULL COMMENT 'Celular de la persona',
  `status_staid` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`perid`),
  INDEX `fk_persona_status1_idx` (`status_staid` ASC),
  CONSTRAINT `fk_persona_status1`
    FOREIGN KEY (`status_staid`)
    REFERENCES `EasyGardenDB`.`status` (`staid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EasyGardenDB`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EasyGardenDB`.`rol` (
  `rolid` INT NOT NULL AUTO_INCREMENT,
  `roldes` VARCHAR(45) NULL COMMENT 'Descripción del rol',
  `status_staid` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`rolid`),
  INDEX `fk_rol_status1_idx` (`status_staid` ASC),
  CONSTRAINT `fk_rol_status1`
    FOREIGN KEY (`status_staid`)
    REFERENCES `EasyGardenDB`.`status` (`staid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EasyGardenDB`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EasyGardenDB`.`usuario` (
  `usrid` INT NOT NULL AUTO_INCREMENT COMMENT 'Id de usuario',
  `usrnom` VARCHAR(45) NULL COMMENT 'Nombre de usuario',
  `usrpwd` VARCHAR(50) NULL,
  `status_staid` VARCHAR(2) NOT NULL,
  `persona_perid` INT NOT NULL,
  `rol_rolid` INT NOT NULL,
  PRIMARY KEY (`usrid`),
  INDEX `fk_usuario_status1_idx` (`status_staid` ASC),
  INDEX `fk_usuario_persona1_idx` (`persona_perid` ASC),
  INDEX `fk_usuario_rol1_idx` (`rol_rolid` ASC),
  CONSTRAINT `fk_usuario_status1`
    FOREIGN KEY (`status_staid`)
    REFERENCES `EasyGardenDB`.`status` (`staid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_perid`)
    REFERENCES `EasyGardenDB`.`persona` (`perid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_rolid`)
    REFERENCES `EasyGardenDB`.`rol` (`rolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EasyGardenDB`.`jardin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EasyGardenDB`.`jardin` (
  `jardid` INT NOT NULL AUTO_INCREMENT COMMENT 'Id de jardin',
  `jarlar` DOUBLE(10,3) NULL COMMENT 'Largo del jardín mas',
  `jaranc` DOUBLE(10,3) NULL COMMENT 'Ancho del jardín mas',
  `jardes` TEXT NULL,
  `jarnup` INT NULL COMMENT 'Número de plantas en el jardín',
  `status_staid` VARCHAR(2) NOT NULL,
  `usuario_usrid` INT NOT NULL,
  PRIMARY KEY (`jardid`),
  INDEX `fk_jardin_status1_idx` (`status_staid` ASC),
  INDEX `fk_jardin_usuario1_idx` (`usuario_usrid` ASC),
  CONSTRAINT `fk_jardin_status1`
    FOREIGN KEY (`status_staid`)
    REFERENCES `EasyGardenDB`.`status` (`staid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jardin_usuario1`
    FOREIGN KEY (`usuario_usrid`)
    REFERENCES `EasyGardenDB`.`usuario` (`usrid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EasyGardenDB`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EasyGardenDB`.`tarea` (
  `tarid` INT NOT NULL AUTO_INCREMENT COMMENT 'Id de tarea',
  `tarnom` VARCHAR(40) NULL,
  `tardes` TEXT NULL COMMENT 'Descripción de la tarea',
  `tarfei` DATE NULL COMMENT 'Fecha inicial de tarea',
  `tarfef` DATE NULL COMMENT 'Fecha de finalización de la tarea',
  `status_staid` VARCHAR(2) NOT NULL,
  `jardin_jardid` INT NOT NULL,
  `usuario_usrid` INT NOT NULL,
  PRIMARY KEY (`tarid`),
  INDEX `fk_tarea_status1_idx` (`status_staid` ASC),
  INDEX `fk_tarea_jardin1_idx` (`jardin_jardid` ASC),
  INDEX `fk_tarea_usuario1_idx` (`usuario_usrid` ASC),
  CONSTRAINT `fk_tarea_status1`
    FOREIGN KEY (`status_staid`)
    REFERENCES `EasyGardenDB`.`status` (`staid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_jardin1`
    FOREIGN KEY (`jardin_jardid`)
    REFERENCES `EasyGardenDB`.`jardin` (`jardid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_usuario1`
    FOREIGN KEY (`usuario_usrid`)
    REFERENCES `EasyGardenDB`.`usuario` (`usrid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EasyGardenDB`.`planta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EasyGardenDB`.`planta` (
  `idplantas` INT NOT NULL AUTO_INCREMENT,
  `planom` VARCHAR(45) NULL COMMENT 'Nombre de la planta',
  `plafal` DATE NULL COMMENT 'Alta de la planta',
  `plaubi` VARCHAR(45) NULL COMMENT 'Ubicación de la planta (sol o sombra)',
  `plades` TEXT NULL COMMENT 'Descripción de la planta',
  `jardin_jardid` INT NOT NULL,
  `status_staid` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idplantas`),
  INDEX `fk_planta_jardin1_idx` (`jardin_jardid` ASC),
  INDEX `fk_planta_status1_idx` (`status_staid` ASC),
  CONSTRAINT `fk_planta_jardin1`
    FOREIGN KEY (`jardin_jardid`)
    REFERENCES `EasyGardenDB`.`jardin` (`jardid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planta_status1`
    FOREIGN KEY (`status_staid`)
    REFERENCES `EasyGardenDB`.`status` (`staid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `EasyGardenDB` ;

-- -----------------------------------------------------
-- Placeholder table for view `EasyGardenDB`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EasyGardenDB`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `EasyGardenDB`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EasyGardenDB`.`view1`;
USE `EasyGardenDB`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
